In [103]:
# Create GDA class

import numpy as np

class GDA:
    
    # Instance attribute
    def __init__(self, train_features, train_labels):
        self.train_features = train_features
        self.train_labels = train_labels
        
    # True and false label subsets
        true_subset = []
        false_subset = []
    
    # Calculating class prior probabilities
        true_count = 0
        false_count = 0
        
        for i,j in zip(self.train_features, self.train_labels):
            if j == 0:
                false_count += 1
                false_subset.append(i)
            else:
                true_count += 1
                true_subset.append(i)
        
        self.true_subset = np.array(true_subset)
        self.false_subset = np.array(false_subset)
        
        self.true_prior = true_count/len(train_features)
        self.false_prior = false_count/len(train_features)
        
    # Calculate feature means for each label class
        self.true_feature_means = np.mean(true_subset, axis = 0)
        self.false_feature_means = np.mean(false_subset, axis = 0)
    
    # Calculating covariance matrix of training features. Result should be a 30 x 30 matrix
        train_features_reshaped = np.reshape(train_features, (train_features.shape[1], train_features.shape[0]))
        self.cov_matrix = np.cov(train_features_reshaped, bias = True)
        
    def gaussian_pdf(self, x, mu, cov):
        mean_diff = x - mu
        
        
        
    

In [104]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import MinMaxScaler

cancer_data = load_breast_cancer()

examples = np.array(cancer_data.data)
labels = np.array(cancer_data.target)

scaler = MinMaxScaler()
examples = scaler.fit_transform(examples)

In [105]:
model_gda = GDA(examples, labels)

In [65]:
model_gda.cov_matrix.shape

(30, 30)

In [102]:
model_gda.cov_matrix

array([[ 4.19138379e-02,  9.11725451e-03,  3.51819178e-03,
         5.57779092e-03,  2.07181261e-03, -2.65108342e-03,
        -3.02715844e-05,  1.45429164e-03, -2.13112550e-03,
        -6.16758493e-03, -4.06708064e-03, -6.27233054e-03,
        -5.03312408e-03, -6.87750108e-03, -3.91670825e-04,
        -4.25248249e-03, -5.69693190e-04, -3.18008363e-03,
        -2.58389558e-03, -5.02261896e-03, -2.07520752e-03,
        -2.71666195e-03, -3.30258650e-03,  2.98378205e-04,
        -1.51561181e-03, -5.31106529e-04,  2.74751888e-03,
         8.25274754e-03,  1.69453903e-03,  3.55482826e-03],
       [ 9.11725451e-03,  3.34668399e-02,  6.64670915e-03,
         1.32630795e-03,  5.56767149e-03,  1.72901087e-03,
         1.78054164e-03,  9.40752980e-04,  9.25926359e-04,
        -2.48621324e-03, -2.60717616e-03, -1.69346884e-04,
        -4.47140830e-03, -4.50799599e-03, -2.48745952e-03,
        -3.50667107e-03, -6.23204140e-03, -3.38083638e-03,
        -5.22346271e-04, -1.85874120e-03, -2.90899982e-

In [73]:
(model_gda.true_subset - model_gda.true_feature_means).shape

(357, 30)

In [81]:
model_gda.true_subset.reshape

array([[3.10426428e-01, 1.57253974e-01, 3.01775966e-01, ...,
        4.42611684e-01, 2.78336290e-01, 1.15112161e-01],
       [2.88655403e-01, 2.02908353e-01, 2.89129984e-01, ...,
        2.50274914e-01, 3.19140548e-01, 1.75718221e-01],
       [1.19409343e-01, 9.23233006e-02, 1.14366664e-01, ...,
        2.13986254e-01, 1.74452986e-01, 1.48825922e-01],
       ...,
       [3.34563870e-01, 5.89786946e-01, 3.28864626e-01, ...,
        3.60137457e-01, 1.35028583e-01, 1.84769776e-01],
       [1.99678167e-01, 6.64863037e-01, 1.85750812e-01, ...,
        0.00000000e+00, 1.97122019e-04, 2.63019808e-02],
       [3.68687586e-02, 5.01521813e-01, 2.85398383e-02, ...,
        0.00000000e+00, 2.57441356e-01, 1.00682146e-01]])

In [106]:
from scipy.stats import multivariate_normal
multivariate_normal.pdf(model_gda.true_subset, model_gda.true_feature_means, model_gda.cov_matrix)

array([2.50794797e+10, 8.98563300e+10, 1.10052075e+10, 5.91401014e+09,
       4.54339048e+09, 1.31430399e+11, 1.78290365e+10, 4.06107489e+10,
       8.22825321e+10, 1.29273293e+11, 1.27057666e+11, 5.22103828e+09,
       1.30806262e+07, 2.92010488e+07, 1.87353780e+09, 1.22188642e+08,
       7.93395986e+09, 1.34677449e+11, 2.78419301e-24, 1.25346991e+11,
       6.50781633e-03, 6.34206041e+11, 3.41720274e+06, 7.38400747e+11,
       7.59937572e+09, 1.23468855e+06, 2.36244657e+11, 7.80945915e+10,
       7.19412564e+06, 2.96190673e+10, 8.03397518e+09, 2.75743951e+11,
       2.76704155e+11, 1.00699126e+09, 5.29842721e+10, 1.00193847e+06,
       6.35428499e+09, 6.82609256e+10, 1.41262576e+11, 1.18789873e+10,
       1.38505487e+11, 2.83064166e+10, 2.22737159e+10, 1.51623467e+09,
       2.48887563e-06, 3.94321059e+09, 3.43039283e+08, 2.08433031e+11,
       4.95221537e+05, 6.62746228e+09, 1.24933721e+09, 5.56213390e+10,
       5.99516934e+10, 6.47758629e+05, 2.36930767e+10, 2.68643548e+09,
      

In [97]:
x = model_gda.true_subset 
mu = model_gda.true_feature_means
cov = model_gda.cov_matrix

In [100]:
np.matmul((x-mu).transpose(), np.linalg.inv(cov))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 30 is different from 357)